import { PercentDiamond } from "lucide-react";

export { default as Header } from "./header/Header";
export { default as Main } from "./main/Main";
export { default as Menu } from "./menu/Menu";
export { default as Section } from "./section/Section";
export { default as Home } from "./home/Home";
export { default as FrontEnd } from "./frontend/FrontEnd";
export { default as BackEnd } from "./BackEnd/BackEnd";
export { default as Mobile } from "./mobile/Mobile";
export { default as Practice } from "./Practice/Practice";
export { default as Code } from "./Code/Code";
export { default as Html } from "./html/Html";
export { default as Boshlangich } from "./html/Boshlangich";
export { default as Orta } from "./html/Orta";
export { default as Mukammal } from "./html/Mukammal";
export { default as HtmlMenu } from "./html/HtmlMenu";
export { default as HtmlSection } from "./html/HtmlSection";
export { default as HtmlBasic } from "../pages/HtmlPages/HtmlBasic";
export { default as HtmlForms } from "../pages/HtmlPages/HtmlForms";
export { default as HtmlElements } from "../pages/HtmlPages/HtmkElements";
export { default as HtmlAttributes } from "../pages/HtmlPages/HtmlAttributes";
export { default as HtmlFrames } from "../pages/HtmlPages/Frames";
export { default as HtmlImages } from "../pages/HtmlPages/HtmlImages";
export { default as HtmlInputTypes } from "../pages/HtmlPages/HtmlInputTypes";
export { default as HtmlLinks } from "../pages/HtmlPages/HtmlLinks";
export { default as HtmlLists } from "../pages/HtmlPages/HtmlLists";
export { default as HtmlSemantics } from "../pages/HtmlPages/HtmlSemantics";
export { default as HtmlTables } from "../pages/HtmlPages/HtmlTables";
export { default as HtmlAudioVideo } from "../pages/HtmlPages/HtmlAudioVideo";
export { default as HtmlBlogInline } from "../pages/HtmlPages/HtmlBlogInline";
export { default as HtmlVide } from "../components/html/HtmlVide";
export { default as HtmlEnties } from "../pages/HtmlPages/HtmlEnties";
export { default as HtmlMeteTegs } from "../pages/HtmlPages/HtmlMeteTegs";

export { default as HtmlResponsiveDesign } from "../pages/HtmlPages/HtmlResponsiveDesign";

export { default as Css } from "./Css/Css";
export { default as CssBoshlangich } from "../components/Css/Boshlangich";
export { default as CssOrta } from "../components/Css/Orta";
export { default as CssMukammal } from "../components/Css/Mukammal";
export { default as CssMenu } from "../components/Css/CssMenu";
export { default as CssSection } from "../components/Css/CssSection";

export { default as HtmlPractice } from "../practicPage/HtmlPractice/HtmlPractice";

export { default as CssPractice } from "../practicPage/CssPractice/CssPractice";


export { default as Temurbek } from "../components/html/Temurbek";

// js pages
export { default as HomeJs } from '../ComponentsJs/HomeJs';
export { default as BoshlangichJs } from "../ComponentsJs/BoshlangichJs";
export { default as Ozgaruvchi } from "../ComponentsJs/pageJs/Ozgaruvchi";
export { default as MalumotTurlari } from "../ComponentsJs/pageJs/MalumotTurlari";
export { default as Operator } from "../ComponentsJs/pageJs/Operator";
export { default as ShartOperatorlar } from "../ComponentsJs/pageJs/ShartOperatorlar";
export { default as SwichCase } from "../ComponentsJs/pageJs/SwichCase";
export { default as ForSkil } from "../ComponentsJs/pageJs/ForSkil";
export { default as WhileSkil } from "../ComponentsJs/pageJs/WhileSkil";
export { default as Funksiyalar } from "../ComponentsJs/pageJs/Funksiyalar";
export { default as ArrayMassiv } from "../ComponentsJs/pageJs/ArrayMassiv";
export { default as ArrayMetod } from "../ComponentsJs/pageJs/ArrayMetod";
export { default as StringMetodlari } from "../ComponentsJs/pageJs/StringMetodlari";
export { default as MathOpyekti } from "../ComponentsJs/pageJs/MathOpyekti";
export { default as DataJsDars } from "../ComponentsJs/pageJs/DataJsDars";
export { default as DomBilanIshlash } from "../ComponentsJs/pageJs/DomBilanIshlash";
export { default as EventsJs } from "../ComponentsJs/pageJs/EventsJs";
export { default as Forms } from "../ComponentsJs/pageJs/Forms";
export { default as LocalStroge } from "../ComponentsJs/pageJs/LocalStroge";
export { default as JsonDars } from "../ComponentsJs/pageJs/JsonDars";
export { default as TryCatch } from "../ComponentsJs/pageJs/TryCatch";
export { default as Asyns } from "../ComponentsJs/pageJs/Asyns";
export { default as Promise } from "../ComponentsJs/pageJs/Promise";
export { default as Es6New } from "../ComponentsJs/pageJs/Es6New";
export { default as ArrowFunk } from "../ComponentsJs/pageJs/ArrowFunk";
export { default as Amaliy } from "../ComponentsJs/pageJs/Amaliy";

// js practice page
export { default as JsPractice } from "../practicPage/JsPractice/JsPractice";
export { default as Number } from "../practicPage/JsPractice/mapFunction/Number";
export { default as AssignDeclar } from "../practicPage/JsPractice/mapFunction/AssignDeclar";
export { default as StringM } from "../practicPage/JsPractice/mapFunction/StringM";
export { default as Boolean } from "../practicPage/JsPractice/mapFunction/Boolean";
export { default as NullAndUndifend } from "../practicPage/JsPractice/mapFunction/NullAndUndifend";
export { default as ChallangeOne } from "../practicPage/JsPractice/mapFunction/ChallangeOne";
export { default as DataArifmetikOperators } from "../practicPage/JsPractice/mapFunction/DataArifmetikOperators";
export { default as ArifmetikShouts } from "../practicPage/JsPractice/mapFunction/ArifmetikShouts";
export { default as ComparisionOperators } from "../practicPage/JsPractice/mapFunction/ComparisionOperators";
export { default as EqualityStrict } from "../practicPage/JsPractice/mapFunction/EqualityStrict";
export { default as LogicalOperators } from "../practicPage/JsPractice/mapFunction/LogicalOperators";
export { default as LogicalOperators2 } from "../practicPage/JsPractice/mapFunction/LogicalOperators2";
export { default as ChallangeTwo } from "../practicPage/JsPractice/mapFunction/ChallangeTwo";
export { default as ChallangeThree } from "../practicPage/JsPractice/mapFunction/ChallangeThree";
export { default as IfStatment } from "../practicPage/JsPractice/mapFunction/IfStatment";
export { default as IfElse } from "../practicPage/JsPractice/mapFunction/IfElse";
export { default as SwitchCasePractice } from "../practicPage/JsPractice/mapFunction/SwitchCasePractice";
export { default as ChallangeFour } from "../practicPage/JsPractice/mapFunction/ChallangeFour";
export { default as OutputWithVribles } from "../practicPage/JsPractice/mapFunction/OutputWithVribles";
export { default as Cast } from "../practicPage/JsPractice/mapFunction/Cast";
export { default as ChallangeFive } from "../practicPage/JsPractice/mapFunction/ChallangeFive";
export { default as Challange6 } from "../practicPage/JsPractice/mapFunction/Challange6";
export { default as ForLop } from "../practicPage/JsPractice/mapFunction/ForLop";
export { default as WhileLoop } from "../practicPage/JsPractice/mapFunction/WhileLoop";
export { default as Break } from "../practicPage/JsPractice/mapFunction/Break";
export { default as Continu } from "../practicPage/JsPractice/mapFunction/Continu";
export { default as Challange7 } from "../practicPage/JsPractice/mapFunction/Challange7";
export { default as DeclareFunkcition } from "../practicPage/JsPractice/mapFunction/DeclareFunkcition";
export { default as Arguments } from "../practicPage/JsPractice/mapFunction/Arguments";
export { default as Return } from "../practicPage/JsPractice/mapFunction/Return";
export { default as RecapChallange9 } from "../practicPage/JsPractice/mapFunction/RecapChallange9";
export { default as Challang10 } from "../practicPage/JsPractice/mapFunction/Challang10";
export { default as DeclaringArray } from "../practicPage/JsPractice/mapFunction/DeclaringArray";
export { default as AccessingArrayElements } from "../practicPage/JsPractice/mapFunction/AccessingArrayElements";
export { default as ModifyingArrays } from "../practicPage/JsPractice/mapFunction/ModifyingArrays";
export { default as ArrayMethods } from "../practicPage/JsPractice/mapFunction/ArrayMethods";
export { default as Challange11 } from "../practicPage/JsPractice/mapFunction/Challange11";
export { default as Challange12 } from "../practicPage/JsPractice/mapFunction/Challange12";
export { default as AstrikPyramid } from "../practicPage/JsPractice/mapFunction/AstrikPyramid";
export { default as TransposeArray } from "../practicPage/JsPractice/mapFunction/TransposeArray";
export { default as GoodConstraction } from "../practicPage/JsPractice/mapFunction/GoodConstraction";
export { default as OrtaJs } from "../ComponentsJs/OrtaJs";
export { default as DomMurrakab } from "../ComponentsJs/pageJsOrta/DomMurrakab";
export { default as FunksiyalarPro } from "../ComponentsJs/pageJsOrta/FunksiyalarPro";
export { default as ArrayObyektlarPro } from "../ComponentsJs/pageJsOrta/ArrayObyektlarPro";
export { default as Animatsiyalar } from "../ComponentsJs/pageJsOrta/Animatsiyalar";
export { default as StorageBrowserApi } from "../ComponentsJs/pageJsOrta/StorageBrowserApi";
export { default as Modullar } from "../ComponentsJs/pageJsOrta/Modullar";
export { default as AsyncJavaScript } from "../ComponentsJs/pageJsOrta/AsyncJavaScript";
export { default as AmaliyPracePage } from "../ComponentsJs/pageJsOrta/AmaliyPracePage";
export { default as dataEs6Xususiylatlari } from "../ComponentsJs/pageJsOrta/Es6Xususiylatlari";
export { default as DebugKonsol } from "../ComponentsJs/pageJsOrta/DebugKonsol";
export { default as ApiBilanIshlash } from "../ComponentsJs/pageJsOrta/ApiBilanIshlash";
export { default as TestingDebug } from "../ComponentsJs/pageJsOrta/TestingDebug";
export { default as Performance } from "../ComponentsJs/pageJsOrta/Performance";
export { default as SecurityPage } from "../ComponentsJs/pageJsOrta/SecurityPage";
export { default as DesignPatterns } from "../ComponentsJs/pageJsOrta/DesignPatterns";
export { default as CleanCode } from "../ComponentsJs/pageJsOrta/CleanCode";
export { default as TypeScriptAsoslar } from "../ComponentsJs/pageJsOrta/TypeScriptAsoslar";
export { default as NpmPackageManagement } from "../ComponentsJs/pageJsOrta/NpmPackageManagement"
export { default as WebpackBundling } from "../ComponentsJs/pageJsOrta/WebpackBundling";
export { default as GitControl } from "../ComponentsJs/pageJsOrta/GitControl";
export { default as MukammalJs } from "../ComponentsJs/MukammalJs";
export { default as JavaScriptAsoslarMukammal } from "../ComponentsJs/pagesMukammal/JavaScriptAsoslarMukammal";
export { default as FunksiyalarScope } from "../ComponentsJs/pagesMukammal/FunksiyalarScope";
export { default as DomManipulatsiya } from "../ComponentsJs/pagesMukammal/DomManipulatsiya";
export { default as dataOopJavaScript } from "../ComponentsJs/pagesMukammal/OopJavaScript"
export { default as Asinxronlik } from "../ComponentsJs/pagesMukammal/Asinxronlik";
export { default as MahalliyMalumotBaza } from "../ComponentsJs/pagesMukammal/MahalliyMalumotBaza";
export { default as ModullarPaketlar } from "../ComponentsJs/pagesMukammal/ModullarPaketlar";
export { default as Testlash } from "../ComponentsJs/pagesMukammal/Testlash";
export { default as FrameworkAsoslar } from "../ComponentsJs/pagesMukammal/FrameworkAsoslar";
export { default as ApiIntegratsiyasi } from "../ComponentsJs/pagesMukammal/ApiIntegratsiyasi";
export { default as MalumotlarBilanIshlash } from "../ComponentsJs/pagesMukammal/MalumotlarBilanIshlash";
export { default as XavfsizlikOptimizatsiya } from "../ComponentsJs/pagesMukammal/XavfsizlikOptimizatsiya";
export { default as PageTailwandcss } from "../componentsTailwand/PageTailwandcss";
export { default as TailwandcssBoshlangich } from '../componentsTailwand/TailwandCssBoshlangich';
export { default as PageTailwandcssOrta } from "../componentsTailwand/PageTailwandcssOrta";
export { default as PageTailwandcssMukammal } from "../componentsTailwand/PageTailwandcssMukammal";
export { default as TailwandCssKirish } from "../componentsTailwand/pagesBoshlangich/TailwandCssKirish";
export { default as LoyihagaOrnatish } from "../componentsTailwand/pagesBoshlangich/LoyihagaOrnatish";
export { default as UtilitySinflar } from "../componentsTailwand/pagesBoshlangich/UtilitySinflar";
export { default as RanglarFonlar } from "../componentsTailwand/pagesBoshlangich/RanglarFonlar";
export { default as MatnUsullari } from "../componentsTailwand/pagesBoshlangich/MatnUsullari";
export { default as ChegaralarBurchaklar } from "../componentsTailwand/pagesBoshlangich/ChegaralarBurchaklar";
export { default as BoshliqniTashkil } from "../componentsTailwand/pagesBoshlangich/BoshliqniTashkil";
export { default as FlexboxAsoslar } from "../componentsTailwand/pagesBoshlangich/FlexboxAsoslar";
export { default as GridTizimiAsoslar } from "../componentsTailwand/pagesBoshlangich/GridTizimiAsoslar";
export { default as ResponsiveDizayn } from "../componentsTailwand/pagesBoshlangich/ResponsiveDizayn";
export { default as TailwandCssAsoslarOrta } from "../componentsTailwand/pagesOrta/TailwandCssAsoslar";
export { default as LayoutJoylashuv } from "../componentsTailwand/pagesOrta/LayoutJoylashuv";
export { default as dataTypographyRuxsatlash } from "../componentsTailwand/dataOrta/dataTypographyRuxsatlash";
export { default as RanglarTemalar } from "../componentsTailwand/pagesOrta/RanglarTemalar";
export { default as InteraktivlikAnimatsiyalar } from "../componentsTailwand/pagesOrta/InteraktivlikAnimatsiyalar";
export { default as Komponentlar } from "../componentsTailwand/pagesOrta/Komponentlar";
export { default as ResponsiveDizaynTailwind } from "../componentsTailwand/pagesOrta/ResponsiveDizayn";
export { default as TailwindCssIntegratsiya } from "../componentsTailwand/pagesOrta/TailwindCssIntegratsiya";
export { default as MaxsusConfogPlugins } from "../componentsTailwand/pagesOrta/MaxsusConfogPlugins";
export { default as AmaliyTailwandOrta } from "../componentsTailwand/pagesOrta/AmaliyTailwandOrta";
export { default as TailwindAsoslarPageMukammal } from "../componentsTailwand/pagesMukammal/TailwindAsoslar";
export { default as UtilityFirstYondashuv } from "../componentsTailwand/pagesMukammal/UtilityFirstYondashuv";
export { default as RanglarGradientlar } from "../componentsTailwand/pagesMukammal/RanglarGradientlar";
export { default as LayoutSpacing } from "../componentsTailwand/pagesMukammal/LayoutSpacing";
export { default as FlexboxGrid } from "../componentsTailwand/pagesMukammal/FlexboxGrid";
export { default as Typography } from "../componentsTailwand/pagesMukammal/Typography";
export { default as ResponsiveDizaynTailwand } from "../componentsTailwand/pagesMukammal/ResponsiveDizayn";
export { default as AnimatsiyalarTransitionsMukammal } from "../componentsTailwand/pagesMukammal/AnimatsiyalarTransitions";
export { default as BordersEffectsTailwand } from "../componentsTailwand/pagesMukammal/BordersEffectsTailwand";
export { default as componentsTailwand } from "../componentsTailwand/pagesMukammal/ComponentsTailwand";
export { default as Customization } from "../componentsTailwand/pagesMukammal/Customization";
export { default as PerformanceMukammal } from "../componentsTailwand/pagesMukammal/PerformanceMukammal";
export { default as RasmlarMedia } from "../componentsTailwand/pagesMukammal/RasmlarMedia";
export { default as JadvallarMukkammal } from "../componentsTailwand/pagesMukammal/JadvallarMukkammal";
export { default as DarkModeMukammal } from "../componentsTailwand/pagesMukammal/DarkModeMukammal";
export { default as PluginsMukammal } from "../componentsTailwand/pagesMukammal/PluginsMukammal";
export { default as dataBestPracticesMukammal } from "../componentsTailwand/dataMukammal/dataBestPractices";
export { default as AmaliyMukammal } from "../componentsTailwand/pagesMukammal/AmaliyMukammal";
export { default as TailwandCssPractice } from "../practicPage/TailwandPractice/TailwandCssPractice";
export { default as HomePageReact } from "../componentsReact/HomePageReact";
export { default as BoshlangichReact } from "../componentsReact/BoshlangichReact";
export { default as OrtaReact } from "../componentsReact/OrtaReact";
export { default as MukammalReact } from "../componentsReact/MukammalReact";
export { default as ReactBoshlagichKirish } from "../componentsReact/pageBoshlangichReact/ReactBoshlagichKirish";
export { default as JsxAsoslarBoshlangich } from "../componentsReact/pageBoshlangichReact/JsxAsoslarBoshlangich";
export { default as ReactComponentsBosh } from "../componentsReact/pageBoshlangichReact/ReactComponentsBosh";
export { default as ReactPropsState } from "../componentsReact/pageBoshlangichReact/ReactPropsState";
export { default as ReactHooksAsoslar } from "../componentsReact/pageBoshlangichReact/ReactHooksAsoslar";
export { default as UseEffectHook } from "../componentsReact/pageBoshlangichReact/UseEffectHook";
export { default as ReactCustomHooks } from "../componentsReact/pageBoshlangichReact/ReactCustomHooks";
export { default as ReactEvents } from "../componentsReact/pageBoshlangichReact/ReactEvents";
export { default as FormsValidatsiya } from "../componentsReact/pageBoshlangichReact/FormsValidatsiya";
export { default as ReactRouterBoshlangich } from "../componentsReact/pageBoshlangichReact/ReactRouterBoshlangich";
export { default as ReactContextApi } from "../componentsReact/pageBoshlangichReact/ReactContextApi";
export { default as ReduxAsoslariBoshlangich } from "../componentsReact/pageBoshlangichReact/ReduxAsoslariBoshlangich";
export { default as ReduxToolkitBoshlangich } from "../componentsReact/pageBoshlangichReact/ReduxToolkitBoshlangich";
export { default as ReactApiIntegration } from "../componentsReact/pageBoshlangichReact/ReactApiIntegration";
export { default as ReactTestingBoshlangich } from "../componentsReact/pageBoshlangichReact/ReactTestingBoshlangich";
export { default as ReactPerformanceBosh } from "../componentsReact/pageBoshlangichReact/ReactPerformanceBosh";
export { default as ReactSecurityBosh } from "../componentsReact/pageBoshlangichReact/ReactSecurityBosh";
export { default as ReactBestPracticesBosh } from "../componentsReact/pageBoshlangichReact/ReactBestPracticesBosh";
export { default as ReactDeploymentBosh } from "../componentsReact/pageBoshlangichReact/ReactDeploymentBosh";
export { default as ReactAmaliyMashqlarBosh } from "../componentsReact/pageBoshlangichReact/ReactAmaliyMashqlarBosh";


// react orta pages
export { default as ReactOrtaReactOptimization } from "../componentsReact/pageOrtaReact/ReactOrtaReactOptimization";
export { default as ReactAdvancedHooksOrta } from "../componentsReact/pageOrtaReact/ReactAdvancedHooksOrta";
export { default as ReactReactPattersOrta } from "../componentsReact/pageOrtaReact/ReactReactPattersOrta";
export { default as ReactStateManagementOrta } from "../componentsReact/pageOrtaReact/ReactStateManagementOrta";
export { default as ReactAdvancedRouting } from "../componentsReact/pageOrtaReact/ReactAdvancedRouting";
export { default as ReactReactTestingOrta } from "../componentsReact/pageOrtaReact/ReactReactTestingOrta";
export { default as ReactServerStateOrta } from "../componentsReact/pageOrtaReact/ReactServerStateOrta";
export { default as ReactReactArchitectureOrta } from "../componentsReact/pageOrtaReact/ReactReactArchitectureOrta";
export { default as ReactPerformanceTuning } from "../componentsReact/pageOrtaReact/ReactPerformanceTuning";
export { default as ReactSecurityBestPractices } from "../componentsReact/pageOrtaReact/ReactSecurityBestPractices";
export { default as ReactComponentLifecycle } from "../componentsReact/pageOrtaReact/ReactComponentLifecycle";
export { default as ReactErrorBoundaries } from '../componentsReact/pageOrtaReact/ReactErrorBoundaries';
export { default as ReactContentApiOrta } from "../componentsReact/pageOrtaReact/ReactContentApiOrta";
export { default as ReactCustomHooksOrta } from "../componentsReact/pageOrtaReact/ReactCustomHooksOrta";
export { default as ReactReactSuspenseOrta } from "../componentsReact/pageOrtaReact/ReactReactSuspenseOrta";
export { default as ReactReactFormsOrta } from "../componentsReact/pageOrtaReact/ReactReactFormsOrta";
export { default as ReactMobileOrta } from "../componentsReact/pageOrtaReact/ReactMobileOrta";
export { default as ReactInternationalizationOrta } from "../componentsReact/pageOrtaReact/ReactInternationalizationOrta";
export { default as ReactReactPluginsOrta } from "../componentsReact/pageOrtaReact/ReactReactPluginsOrta";


// react mukammal pages
export { default as ReactAdvancedComponentPatterns } from "../componentsReact/pageMukammalReact/ReactAdvancedComponentPatterns";
export { default as ReactPerformanceOptimizationPro } from "../componentsReact/pageMukammalReact/ReactPerformanceOptimizationPro";
export { default as ReactCustomHooksEngineering } from "../componentsReact/pageMukammalReact/ReactCustomHooksEngineering";
export { default as ReactStateManagementArchi } from "../componentsReact/pageMukammalReact/ReactStateManagementArchi";
export { default as ReactAdvancedMukammal } from "../componentsReact/pageMukammalReact/ReactAdvancedMukammal";
export { default as ReactTestingMukammal } from "../componentsReact/pageMukammalReact/ReactTestingMukammal";
export { default as ReactInternalsMukammal } from "../componentsReact/pageMukammalReact/ReactInternalsMukammal";
export { default as ReactAdvancedPatternsMukammal } from "../componentsReact/pageMukammalReact/ReactAdvancedPatternsMukamma"
export { default as ReactSecurityAuthMukammal } from "../componentsReact/pageMukammalReact/ReactSecurityAuthMukammal";
export { default as ReactComplexFormMukammal } from "../componentsReact/pageMukammalReact/ReactComplexFormMukammal";
export { default as ReactAdvancedRoutingMukammal } from "../componentsReact/pageMukammalReact/ReactAdvancedRoutingMukammal";
export { default as ReactCodeSplittingMukammal } from "../componentsReact/pageMukammalReact/ReactCodeSplittingMukammal";
export { default as ReactSsrMasteryMukammal } from "../componentsReact/pageMukammalReact/ReactSsrMasteryMukammal";
export { default as ReactStateMachinesMukammal } from "../componentsReact/pageMukammalReact/ReactStateMachinesMukammal";
export { default as ReactMicroFrontEndMukammal } from '../componentsReact/pageMukammalReact/ReactMicroFrontEndMukammal';
export { default as ReactEnterpriseMukammal } from "../componentsReact/pageMukammalReact/ReactEnterpriseMukammal";
export { default as ReactAdvancedTypeMukammal } from "../componentsReact/pageMukammalReact/ReactAdvancedTypeMukammal";
export { default as ReactGraphQlMukammal } from "../componentsReact/pageMukammalReact/ReactGraphQlMukammal";
export { default as ReactCiCdMukammal } from "../componentsReact/pageMukammalReact/ReactCiCdMukammal";
export { default as ReactQueryDataMukammal } from "../componentsReact/pageMukammalReact/ReactQueryDataMukammal";
export { default as ReactReactNativeMukammal } from "../componentsReact/pageMukammalReact/ReactReactNativeMukammal";
export { default as ReactReduxToolkitMukammal } from '../componentsReact/pageMukammalReact/ReactReduxToolkitMukammal';
export { default as ReactTestingLibraryMukammal } from "../componentsReact/pageMukammalReact/ReactTestingLibraryMukammal";
export { default as ReactWebpackBundlingMukammal } from '../componentsReact/pageMukammalReact/ReactWebpackBundlingMukammal';
export { default as ReactArchitectureMukammal } from "../componentsReact/pageMukammalReact/ReactArchitectureMukammal";
export { default as ReactErrorBoundariesMukammal } from "../componentsReact/pageMukammalReact/ReactErrorBoundariesMukammal";
export { default as ReactPerformanceMukammal } from "../componentsReact/pageMukammalReact/ReactPerformanceMukammal";
export { default as ReactPrognessiveWebMukammal } from "../componentsReact/pageMukammalReact/ReactPrognessiveWebMukammal";
export { default as ReactAccessibilityMukammal } from "../componentsReact/pageMukammalReact/ReactAccessibilityMukammal";
export { default as ReactInternationalizationMukammal } from "../componentsReact/pageMukammalReact/ReactInternationalizationMukammal";
export { default as ReactServerComponentsMukammal } from "../componentsReact/pageMukammalReact/ReactServerComponentsMukammal";


// komputer savodxonligi
export { default as KomputerSavodxonlik } from "./komputerSavodxonli/KomputerSavodxonlik";
export { default as KomputerTuzilishi } from "../componentsKamputerSavod/KomputerTuzilishi/KomputerTuzilishi";
export { default as ReactOperationTizim } from '../componentsKamputerSavod/OperationTizim/ReactOperationTizim';
export { default as MatnMuharririWord } from "../componentsKamputerSavod/MatnMuharririWord/MatnMuharririWord";
export { default as ReactElektronJadvallar } from "../componentsKamputerSavod/ElektronJadvallar/ReactElektronJadvallar";
export { default as ReactKomputerTaqdimot } from "../componentsKamputerSavod/KomputerTaqdimotlar/ReactKomputerTaqdimot";
export { default as ReactInternetSavod } from "../componentsKamputerSavod/KomputerInternet/ReactInternetSavod";
export { default as KomputerXavfsizlikOne } from "../componentsKamputerSavod/Xavfsizlik/KomputerXavfsizlikOne";
export { default as BlutliTexnologiyalar } from "../componentsKamputerSavod/BlutliTexnologiyalar/BlutliTexnologiyalar";
export { default as Profile } from "../adminPage/Profile";
export { default as Settings } from "../adminPage/Setting";
export { default as Foydalanuvchilar } from "../adminPage1/Foydalanuvchilar";
export { default as Statistika } from "../adminPage1/Statistika";
export { default as Message } from "../adminPage1/Message";
export { default as Payments } from '../PullikObunalar/Payments';
export { default as PaymentPage } from "../PullikObunalar/PaytmentPage";
export { default as PaymentPage1 } from "../PullikObunalar/PaymentPage1";
export { default as OnlineKursObuna } from "../PullikObunalar/OnlineKursObuna";
export { default as FrontEndKurslar } from "../kursTolovlar/frontEnd/FrontEndKurslar";
export { default as FrontVide } from "../VideDarslar/frontEnd/FrontVide";
export { default as KursTolovlariHammasi } from "../PullikObunalar/KursTolovlariHammasi";
export { default as PremiumKurslar } from "../premiumMenuItemItems/PremiumKurslar/PremiumKurslar";
export {default as ShaxsiyMentorlik} from "../premiumMenuItemItems/ShaxsiyMentor/ShaxsiyMentorlik";
export {default as QoshimchaMateriallar} from "../premiumMenuItemItems/qoshimchaMateriallar/QoshimchaMateriallar";
export {default as Shertifikatlar} from "../premiumMenuItemItems/Shertifikatlar/Shertifikatlar";
export {default as PremiumAmaliyot} from "../premiumMenuItemItems/PremiumAmaliyot/PremiumAmaliyot";
export {default as PremiumFoyda} from "../adminPage1/PremiumFoyda";
export {default as UmumiyStatistika} from "../adminPage1/UmumiyStatistika";
export {default as PremiumStatistika} from '../adminPage1/PremiumStatistika';
export {default as PremiumStatistika50} from "../adminPage1/PremiumStatistika50";
export {default as AllMessages} from "../messages/AllMessages";
export {default as AiHelp} from "../aiHelp/AiHelp";