export { default as Header } from "./header/Header";
export { default as Main } from "./main/Main";
export { default as Menu } from "./menu/Menu";
export { default as Section } from "./section/Section";
export { default as Home } from "./home/Home";
export { default as FrontEnd } from "./frontend/FrontEnd";
export { default as BackEnd } from "./BackEnd/BackEnd";
export { default as Mobile } from "./mobile/Mobile";
export { default as Practice } from "./Practice/Practice";
export { default as Code } from "./Code/Code";
export { default as Html } from "./html/Html";
export { default as Boshlangich } from "./html/Boshlangich";
export { default as Orta } from "./html/Orta";
export { default as Mukammal } from "./html/Mukammal";
export { default as HtmlMenu } from "./html/HtmlMenu";
export { default as HtmlSection } from "./html/HtmlSection";
export{default as HtmlBasic} from "../pages/HtmlPages/HtmlBasic";
export{default as HtmlForms} from "../pages/HtmlPages/HtmlForms";
export {default as HtmlElements} from "../pages/HtmlPages/HtmkElements";
export {default as HtmlAttributes} from "../pages/HtmlPages/HtmlAttributes";
export {default as HtmlFrames} from "../pages/HtmlPages/Frames";
export {default as HtmlImages} from "../pages/HtmlPages/HtmlImages";
export{default as HtmlInputTypes} from "../pages/HtmlPages/HtmlInputTypes";
export {default as HtmlLinks} from "../pages/HtmlPages/HtmlLinks";
export {default as HtmlLists} from "../pages/HtmlPages/HtmlLists";
export {default as HtmlSemantics} from "../pages/HtmlPages/HtmlSemantics";
export {default as HtmlTables} from "../pages/HtmlPages/HtmlTables";